pull_request_title: 'i18n: update crowdin translation'
commit_message: 'i18n: update translations for `%language%`'
append_commit_message: false
files:
  - source: /src/main/resources/assets/hytools/lang/en_US.lang
    translation: /src/main/resources/assets/hytools/lang/%locale_with_underscore%.lang
